# Generated by Django 3.1.5 on 2021-01-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210123_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_eleitor', models.CharField(max_length=20)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('conjuge', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
